### ISSUE TITLE
Make a preliminary release of pyre

### ISSUE THREAD

**Issue by piyushrpt** [pyre/pyre#22]
Would it be possible to make an initial release for pyre? So that we can automate the installation of a basic version by creating a conda package.

**Comment by aivazis** [comment]
Piyush,

Certainly. Let’s chat asap so i can understand exactly what you need. We should discuss the tool chain involved, and whether pyre could/should absorb the release mechanism. 

-- Michael

**Comment by lijun99** [comment]
May I join when you have the discussion? I also hope for a more standardized installation method for pyre (as well as altar). 

I like the new mm. We should first standardize it to a regular tool chain for other packages. But since it depends on some basic features of pyre, we could 
a) install new mm with a basic pyre included, like pyre-boot.zip) , which can easily be done by python setuptools, we then use new mm (in setup.py, or conda build.sh) to compile/install pyre/isce/altar ...;  
b) merge new mm into pyre, then pyre calls the included mm to compile itself, 
c) separate pyre into two parts, one with (mostly) python codes which can be compiled/installed by  python setuptools; and another with all the extensions (where all library related compilation complexity arises): rearranging them into new format conforming to new mm (e.g., move all gsl code into a gsl directory, with lib, ext, gsl(python) sub-directories).

**Comment by aivazis** [comment]
Lijun,

The new mm downloads the bootstrap version of pyre automatically when importing pyre fails. Isn’t this enough to get things going?

-- Michael

**Comment by lijun99** [comment]
Michael, 

The new mm works fine as a standalone package. My points are
1) install mm to python site-packages or conda as any other standard python package; 
2) then use new mm to compile pyre and install it to site-packages; for this, we might need to rearrange pyre, and write a setup.py or conda build to use mm.

**Comment by piyushrpt** [comment]
Need a similar release for "config" as well to allow the recipe to pull in the tarball to build "pyre".

**Comment by aivazis** [comment]
Piyush,

I released 3.5.0 and invited Ryan to collaborate. Let me know if you need anything else to move this forward.

— Michael
